import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { cn } from '~/lib/utils/ui'

import { ClientProviders } from './client-providers'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-black font-sans text-foreground antialiased',
          inter.variable,
        )}
      >
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  )
}
